/* Generated By:JavaCC: Do not edit this line. LCageTreeConstants.java Version 5.0 */
package parser;

public interface LCageTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVARIOSFUNC = 1;
  public int JJTMAIN = 2;
  public int JJTVARDECL = 3;
  public int JJTTIPO = 4;
  public int JJTATRIBUICAO = 5;
  public int JJTATRIBUIR = 6;
  public int JJTTALVEZLISTAEXP = 7;
  public int JJTLOOP = 8;
  public int JJTLISTAEXP = 9;
  public int JJTLISTAEXP2 = 10;
  public int JJTMDECLARACAO = 11;
  public int JJTEXP = 12;
  public int JJTFATOR = 13;
  public int JJTTALVEZFATOR = 14;
  public int JJTSEQCOMANDOS = 15;
  public int JJTCOMANDO = 16;
  public int JJTTALVEZELSE = 17;
  public int JJTEXP_LOGICAS = 18;
  public int JJTFATOR_LOGICO = 19;
  public int JJTFUNC = 20;
  public int JJTTALVEZLISTAARG = 21;
  public int JJTLISTAARG = 22;
  public int JJTLISTAARG2 = 23;


  public String[] jjtNodeName = {
    "Start",
    "VariosFunc",
    "Main",
    "VarDecl",
    "Tipo",
    "Atribuicao",
    "Atribuir",
    "TalvezListaExp",
    "Loop",
    "ListaExp",
    "ListaExp2",
    "Mdeclaracao",
    "Exp",
    "Fator",
    "TalvezFator",
    "SeqComandos",
    "Comando",
    "TalvezElse",
    "Exp_logicas",
    "Fator_logico",
    "Func",
    "TalvezListaArg",
    "ListaArg",
    "ListaArg2",
  };
}
/* JavaCC - OriginalChecksum=0c104b4dd2c53c19c743aaae852783a3 (do not edit this line) */
