/* Generated By:JJTree&JavaCC: Do not edit this line. LCageConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LCageConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMENTARIO = 5;
  /** RegularExpression Id. */
  int COMENTARIOS = 6;
  /** RegularExpression Id. */
  int COM = 7;
  /** RegularExpression Id. */
  int MAIN = 8;
  /** RegularExpression Id. */
  int ACHAVES = 9;
  /** RegularExpression Id. */
  int FCHAVES = 10;
  /** RegularExpression Id. */
  int APARENT = 11;
  /** RegularExpression Id. */
  int FPARENT = 12;
  /** RegularExpression Id. */
  int VAR = 13;
  /** RegularExpression Id. */
  int PTOVIRGULA = 14;
  /** RegularExpression Id. */
  int IF = 15;
  /** RegularExpression Id. */
  int ELSE = 16;
  /** RegularExpression Id. */
  int WHILE = 17;
  /** RegularExpression Id. */
  int DO = 18;
  /** RegularExpression Id. */
  int RETURN = 19;
  /** RegularExpression Id. */
  int PRINT = 20;
  /** RegularExpression Id. */
  int FUNCAO = 21;
  /** RegularExpression Id. */
  int INT = 22;
  /** RegularExpression Id. */
  int FLOAT = 23;
  /** RegularExpression Id. */
  int BOOL = 24;
  /** RegularExpression Id. */
  int TRUE = 25;
  /** RegularExpression Id. */
  int FALSE = 26;
  /** RegularExpression Id. */
  int VIRGULA = 27;
  /** RegularExpression Id. */
  int ATRIB = 28;
  /** RegularExpression Id. */
  int OP = 29;
  /** RegularExpression Id. */
  int OPL = 30;
  /** RegularExpression Id. */
  int LETRA = 31;
  /** RegularExpression Id. */
  int DIGITO = 32;
  /** RegularExpression Id. */
  int DIGITOS = 33;
  /** RegularExpression Id. */
  int LD = 34;
  /** RegularExpression Id. */
  int FSUB = 35;
  /** RegularExpression Id. */
  int FOP = 36;
  /** RegularExpression Id. */
  int EXPOP = 37;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 38;
  /** RegularExpression Id. */
  int TOKEN_NUMLIT = 39;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<COMENTARIO>",
    "<COMENTARIOS>",
    "<COM>",
    "\"main\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"cage\"",
    "\";\"",
    "\"cageif\"",
    "\"elcages\"",
    "\"ncage\"",
    "\"docage\"",
    "\"recage\"",
    "\"pricage\"",
    "\"funCage\"",
    "\"icage\"",
    "\"fcage\"",
    "\"bcage\"",
    "\"trucage\"",
    "\"falcage\"",
    "\",\"",
    "\":=\"",
    "<OP>",
    "<OPL>",
    "<LETRA>",
    "<DIGITO>",
    "<DIGITOS>",
    "<LD>",
    "<FSUB>",
    "<FOP>",
    "<EXPOP>",
    "<IDENTIFICADOR>",
    "<TOKEN_NUMLIT>",
  };

}
